src/src/Entity/Classroom.php
<?php

namespace App\Entity;

use App\Repository\ClassroomRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClassroomRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Classroom
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_active;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_created;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    /**
     * @param bool|null $is_active
     * @return $this
     */
    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    /**
     * @param \DateTimeInterface|null $date_created
     * @return $this
     */
    public function setDateCreated(?\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    /******************** END Getters and Setters ********************/

    /**
     * @ORM\PrePersist
     *
     * @throws \Exception
     */
    public function onPrePersist()
    {
        $this->date_created = new \DateTime('now');
    }
}

src/src/Controller/ClassroomController.php
<?php

namespace App\Controller;

use App\Entity\Classroom;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Serializer\Encoder\JsonDecode;

class ClassroomController extends AbstractController
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * @var JsonDecode
     */
    private $jsonDecoder;

    /**
     * @var \App\Repository\ClassroomRepository|\Doctrine\Persistence\ObjectRepository
     */
    private $classroomRepository;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
        $this->jsonDecoder = new JsonDecode();
        $this->classroomRepository = $this->entityManager->getRepository(Classroom::class);
    }

    /**
     * @Route("/classroom/list", methods={"GET"})
     * @return Response
     */
    public function getClassroomList(): Response
    {
        return $this->render('classroom/list.html.twig', [
            'classrooms' => $this->classroomRepository->findAll()
        ]);
    }

    /**
     * @Route("/classroom/{id}",  methods={"GET"}, requirements={"id"="\d+"})
     * @param $id
     * @return Response
     */
    public function getClassroomItem($id)
    {
        $classroom = $this->classroomRepository->find($id);

        if (!$classroom) {
            throw new NotFoundHttpException("classroom_not_found");
        }

        return $this->render('classroom/item.html.twig', [
            'classroom' => $classroom
        ]);
    }

    /**
     * @Route("/classroom", methods={"POST"})
     *
     * @param Request $request
     * @return Response
     */
    public function createClassroom(Request $request)
    {
        $parameters = $this->jsonDecoder->decode($request->getContent(), 'array');

        $classroom = new Classroom();
        $classroom->setName($parameters->name);
        $classroom->setIsActive($parameters->isActive);

        $this->entityManager->persist($classroom);
        $this->entityManager->flush();

        return new Response('classroom.added');
    }

    /**
     * @Route("/classroom/{id}", methods={"PATCH"})
     *
     * @param $id
     * @param Request $request
     * @return Response
     */
    public function updateClassroom($id, Request $request)
    {
        $parameters = $this->jsonDecoder->decode($request->getContent(), 'array');

        $classroom = $this->classroomRepository->find($id);

        if (!$classroom) {
            throw new NotFoundHttpException("classroom_not_found");
        }

        $classroom->setName($parameters->name);
        $classroom->setIsActive($parameters->isActive);

        $this->entityManager->persist($classroom);
        $this->entityManager->flush();

        return new Response('classroom.updated');
    }

    /**
     * @Route("/classroom/{id}", methods={"DELETE"})
     *
     * @param $id
     * @return Response
     */
    public function deleteClassroom($id)
    {
        $classroom = $this->classroomRepository->find($id);

        if (!$classroom) {
            throw new NotFoundHttpException("classroom_not_found");
        }

        $this->entityManager->remove($classroom);
        $this->entityManager->flush();

        return new Response('classroom.deleted');
    }
}

src/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

src/templates/classroom/item.html.twig
<h1>Classroom</h1>

<table style="border: 1px">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Is Active</th>
        <th>Date Created</th>
    </tr>

    <tr>
        <td>{{ classroom.id|e }}</td>
        <td>{{ classroom.name|e }}</td>
        <td>{{ classroom.isActive ? 'Yes':'No' }}</td>
        <td>{{ classroom.dateCreated|date("m/d/Y") }}</td>
    </tr>

</table>

src/templates/classroom/list.html.twig
<h1>Classrooms</h1>

<table style="border: 1px">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Is Active</th>
        <th>Date Created</th>
    </tr>
    {% for classroom in classrooms %}
        <tr>
            <td>{{ classroom.id|e }}</td>
            <td>{{ classroom.name|e }}</td>
            <td>{{ classroom.isActive ? 'Yes':'No'  }}</td>
            <td>{{ classroom.dateCreated|date("m/d/Y") }}</td>
        </tr>
    {% endfor %}

</table>